# This is a basic workflow to help you get started with Actions

name: first-workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Step 1
        run: echo Hello from Step 1!

      # Runs a set of commands using the runners shell
      - name: Step 2
        run: |
          echo Hello from Step 2!
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Cowsays
        uses: mscoutermarsh/cowsays-action@v1
        with:
            text: Moooooo!
            color: 'cyan'       
